theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

permalink: /:categories/:year/:month/:day/:title

# Non-jekyll custom config variables
copyright: Stephen Humphries
title: Stephen's Site
url: https://shumphries.ca

source_url: https://github.com/sjahu/sjahu.github.io
source_branch: main

timezone: America/Toronto

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - setup.sh
