theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post

# Non-jekyll custom config variables
copyright: Stephen Humphries
title: Stephen's Site
url: https://shumphries.ca

timezone: America/Toronto

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - setup.sh